import { Doctor } from '@/types'

export const DOCTORS: Doctor[] = [
  {
    id: '1',
    name: "Assoc. Prof. (C) Dato' Dr. Ahmad Faizal Mohd Perdaus",
    department: 'Respiratory Medicine / Internal Medicine',
    specialty: 'Respiratory Medicine, Internal Medicine',
    qualifications: 'MBBS (UKM, 1992), M.MED Internal Medicine (UKM, 2001)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dato-dr-ahmad-faizal-mohd-perdaus',
    extraInfo: 'Associate Professor (Clinical) in Respiratory and Internal Medicine. President of MERCY Malaysia since 2009.',
  },
  {
    id: '2',
    name: 'Assoc. Prof. Dr. Aminudin Rahman Mohd Mydin',
    department: 'Clinical and Radiation Oncology',
    specialty: 'Clinical Oncology, Radiation Oncology',
    qualifications: 'MBBS (UM, 1999), FRCR Clinical Oncology (RCR London, 2006), Fellowship Radiation Oncology (Canada, 2008)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-aminudin-rahman-mohd-mydin',
    extraInfo: 'Head of Oncology at KPJ DSH. Cancer and Radiosurgery Centre (Oncology Centre of Excellence).',
  },
  {
    id: '3',
    name: 'Assoc. Prof. Dr. Mohd Daud Sulaiman',
    department: 'Cardiology / Internal Medicine',
    specialty: 'Interventional Cardiology, Internal Medicine',
    qualifications: 'MD (UKM, 1990), MMED Internal Medicine (UKM, 1997), Fellowship Cardiology (UK)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-mohd-daud-sulaiman',
    extraInfo: 'Specialises in interventional cardiology and internal medicine.',
  },
  {
    id: '4',
    name: 'Assoc. Prof. Dr. Naveen A/L Rajadurai',
    department: 'Radiology',
    specialty: 'Musculoskeletal Radiology, Diagnostic and Interventional Radiology',
    qualifications: 'Clinical Associate Professor at KPJ International College Penang',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/dr-naveen-rajadurai',
    extraInfo: 'Head of Radiology Services at KPJ Damansara Specialist Hospital.',
  },
  {
    id: '5',
    name: 'Assoc. Prof. Dr. Rashdan Zaki Mohamed',
    department: 'Paediatrics and Paediatric Endocrinology',
    specialty: 'General Paediatrics, Paediatric Endocrinology',
    qualifications: 'MBBS (UM, 2004), MPaeds (UM, 2013), Fellowship Paediatric Endocrinology',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/rashdan-zaki-mohamed',
    extraInfo: 'Head of Specialty (Paediatrics) at KPJ Healthcare Bhd. Specialises in paediatric endocrinology, growth disorders, and diabetes in children.',
  },
  {
    id: '6',
    name: 'Datin Dr. Nazariah Aiza Harun',
    department: 'Psychiatry',
    specialty: 'Child and Adolescent Psychiatry',
    qualifications: 'Specialist in Child and Adolescent Psychiatry',
    languages: ['English', 'Malay'],
    extraInfo: 'Consultant Child and Adolescent Psychiatrist at KPJ Damansara Specialist Hospital.',
  },
  {
    id: '7',
    name: 'Datin Dr. Vasantha Kumari Mathews',
    department: 'Paediatrics',
    specialty: 'General Paediatrics',
    qualifications: 'MBBS (UM), MRCP (UK)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/datin-dr-vasantha-kumari-mathews',
    extraInfo: 'Experienced Consultant Paediatrician.',
  },
  {
    id: '8',
    name: 'Datin Dr. Wahida Abdul Latif',
    department: 'Anaesthesiology and Critical Care',
    specialty: 'Anaesthesiology, Critical Care',
    qualifications: 'MBBS (UM), M.MED Anaesthesiology (UKM)',
    languages: ['English', 'Malay'],
    extraInfo: 'Consultant Anaesthesiologist and Critical Care specialist.',
  },
  {
    id: '9',
    name: 'Datin Wira Dr. Priyya Subramaniam',
    department: 'Dermatology',
    specialty: 'Dermatology, Internal Medicine',
    qualifications: 'Specialist in Dermatology',
    languages: ['English', 'Malay', 'Tamil'],
    extraInfo: 'Consultant Dermatologist at KPJ Damansara Specialist Hospital.',
  },
  {
    id: '10',
    name: "Dato' Dr. Kamil Noordin",
    department: 'Urology',
    specialty: 'Urology — Endourology, Stone Disease, Urinary Incontinence, Urological Tumours',
    qualifications: 'FRCS (RCS Edinburgh), Fellowship Endourology (World Endourological Society and UCLA)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/doctor/dato-dr-kamil-noordin',
    extraInfo: 'Member of Malaysian Urological Association (MUA) and American Urological Association (AUA).',
  },
  {
    id: '11',
    name: "Dato' Dr. Musa Mohd Nordin",
    department: 'Paediatrics and Neonatology',
    specialty: 'Paediatrics, Neonatology',
    qualifications: 'MBBCh (University of Wales, 1982), MRCP (UK), FRCP (Edinburgh), FRCPCH, FAMM',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dato-dr-musa-mohd-nordin',
    extraInfo: 'Honorary Treasurer of the Malaysian Paediatric Association. FIMA Lifetime Achievement Award 2017.',
  },
  {
    id: '12',
    name: "Dato' Dr. Sivamohan S. Namasivayam",
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology, Gynaecological Oncology',
    qualifications: 'MBBS (1979), MRCOG (1986), Fellowship Gynaecology and Oncology (UK, 1992), FRCOG (1999)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/dato-dr-sivamohan-n',
    extraInfo: 'In private practice at KPJ DSH since 1997. Over 40 years of experience.',
  },
  {
    id: '13',
    name: "Dato' Dr. Wan Nik Ahmad Mustafa",
    department: 'Anaesthesiology',
    specialty: 'Anaesthesiology',
    qualifications: 'MBBS, Diploma in Anaesthetics, FRCS (Anaesthesia)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dato-dr-wan-nik-ahmad-mustafa',
    extraInfo: 'Senior Consultant Anaesthesiologist.',
  },
  {
    id: '14',
    name: "Dato' Dr. Zainudin Md Zin",
    department: 'Respiratory Medicine / Internal Medicine',
    specialty: 'Internal Medicine, Respiratory Medicine — Pulmonology, Asthma, COPD, Sleep-Disordered Breathing',
    qualifications: 'MD (UKM, 1982), MRCP (RCP UK, 1986), FRCP (Edinburgh, 1996)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dato-dr-zainudin-md-zin',
    extraInfo: 'Pioneer of KPJ DSH Sleep Diagnostic Laboratory (1997). First Chairman of the Lung Foundation of Malaysia.',
  },
  {
    id: '15',
    name: "Dato' Dr. Zurin Adnan Abd Rahman",
    department: 'Neurosurgery',
    specialty: 'Neurosurgery — Brain, Spine, Spinal Neurosurgery',
    qualifications: 'MD, Master of Surgery Neurosurgery (UKM, 1995), Clinical Fellowship Neurosurgery (Royal North Shore Hospital Sydney)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dato-dr-zurin-adnan-abd-rahman',
    extraInfo: 'Over 38 years of experience in neurosurgery.',
  },
  {
    id: '16',
    name: 'Datuk Dr. Ahmad Shukri bin Md Salleh',
    department: 'Gastroenterology',
    specialty: 'Gastroenterology, Endoscopy',
    qualifications: 'Consultant Gastroenterologist',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/datuk-dr-ahmad-shukri-md-salleh',
    extraInfo: 'Expertise in diagnostic and therapeutic endoscopy.',
  },
  {
    id: '17',
    name: 'Datuk Dr. Hanif Hussein',
    department: 'Vascular Surgery',
    specialty: 'General Surgery, Vascular Surgery',
    qualifications: 'MD (UKM), MS General Surgery (UKM, 1999), Fellowship Vascular Surgery (Hull Royal Infirmary UK, 2003)',
    languages: ['English', 'Malay'],
    extraInfo: 'Specialises in peripheral vascular disease and vascular reconstruction.',
  },
  {
    id: '18',
    name: 'Datuk Dr. Kathiresan Valliappa',
    department: 'Anaesthesiology and Critical Care',
    specialty: 'Anaesthesiology, Cardiac Anaesthesia, Critical Care',
    qualifications: 'MBBS (Madras), Master of Anaesthesiology',
    languages: ['English', 'Malay', 'Tamil'],
    extraInfo: 'Senior Consultant specialising in cardiac anaesthesia and critical care.',
  },
  {
    id: '19',
    name: 'Datuk Dr. Mohammad Iqbal Mohammad Sarwar',
    department: 'Gastroenterology and Hepatology',
    specialty: 'Gastroenterology, Hepatology',
    qualifications: 'Consultant Gastroenterologist and Hepatologist',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/datuk-dr-mohammad-iqbal-mohammad-sarwar',
  },
  {
    id: '20',
    name: 'Dr. Abdul Gafoor Abdul Mubarak',
    department: 'General / Colorectal / Bariatric / Thoracic Surgery',
    specialty: 'General Surgery, Colorectal Surgery, Bariatric Surgery, Thoracic Surgery',
    qualifications: 'MBBS (IIUM), Master of Surgery (USM), MRCSEd; Fellowships in Bariatric, Colorectal, and Thoracic Surgery',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/abdul-gafoor-abdul-mubarak',
    extraInfo: 'Founder and President of the Malaysian Society of Aesthetic Gynecology.',
  },
  {
    id: '21',
    name: 'Dr. Abdul Malik Mohamed Hussein',
    department: 'Orthopaedic Surgery',
    specialty: 'Orthopaedic Surgery — Joint Replacement, Spine Surgery',
    qualifications: 'MBBS (UM, 1983), FRCS (RCP&S Glasgow, 1992), FSSHK (HKU, 1997)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-abdul-malik-mohamed-hussein',
  },
  {
    id: '22',
    name: 'Dr. Ahmad Zakiyy Mohamed',
    department: 'Internal Medicine / Haematology',
    specialty: 'Internal Medicine, Haematology',
    qualifications: 'Consultant in Internal Medicine and Haematology',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-ahmad-zakiyy-mohamed',
  },
  {
    id: '23',
    name: 'Dr. Alvin Teo Shou Wai',
    department: 'Orthopaedic Surgery',
    specialty: 'Orthopaedic Surgery, Trauma Surgery',
    qualifications: 'Consultant Orthopaedic and Trauma Surgeon',
    languages: ['English', 'Malay', 'Mandarin'],
  },
  {
    id: '24',
    name: 'Dr. Amber Haseeb',
    department: 'Orthopaedic Surgery',
    specialty: 'Orthopaedic Surgery — Foot and Ankle Surgery',
    qualifications: 'MBBS (IIUM), MS Orthopaedics (UM), Fellowship Foot and Ankle Surgery (Singapore and UPM)',
    languages: ['English', 'Malay', 'Hindi'],
  },
  {
    id: '25',
    name: 'Dr. Anand Raj A/L Silveraju',
    department: 'Cardiology',
    specialty: 'Cardiology — Interventional Cardiology, Cardiac Arrhythmias',
    qualifications: 'BSc Medical Sciences (UM), MD (Crimea State Medical University), MMed Internal Medicine (UM)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/anand-raj-al-silveraju',
  },
  {
    id: '26',
    name: 'Dr. Awal Hassan',
    department: 'ENT / Otorhinolaryngology',
    specialty: 'Ear, Nose and Throat Surgery',
    qualifications: 'MBBS (UM), FRCS (Edinburgh)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-awal-hassan',
  },
  {
    id: '27',
    name: 'Dr. Azhani Akmar Azhar',
    department: 'Nephrology and Internal Medicine',
    specialty: 'Nephrology, Internal Medicine',
    qualifications: 'Consultant Nephrologist',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-azhani-akmar-azhar',
  },
  {
    id: '28',
    name: 'Dr. Azlina Hj Ab Rani',
    department: 'ENT / Otorhinolaryngology',
    specialty: 'Ear, Nose and Throat Surgery',
    qualifications: 'Consultant ENT Surgeon',
    languages: ['English', 'Malay'],
  },
  {
    id: '29',
    name: 'Dr. Azmi Abdul Rashid',
    department: 'Neurology / Internal Medicine',
    specialty: 'Internal Medicine, Neurology',
    qualifications: 'MD (USM, 1987), MMed Internal Medicine (UKM, 1995)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-azmi-abdul-rashid',
  },
  {
    id: '30',
    name: 'Dr. Azraai Bahari',
    department: 'Anaesthesiology',
    specialty: 'Anaesthesiology',
    qualifications: 'MD (UKM, reg. 1987), M.MED Anaesthesiology',
    languages: ['English', 'Malay'],
  },
  {
    id: '31',
    name: 'Dr. Bavani Naidu A/P Ragupathy Naidu',
    department: 'Anaesthesiology and Critical Care',
    specialty: 'Critical Care Medicine, Anaesthesiology',
    qualifications: 'Consultant in Critical Care Medicine and Anaesthesiology',
    languages: ['English', 'Malay', 'Tamil'],
  },
  {
    id: '32',
    name: 'Dr. Chan Siew How',
    department: 'General Surgery',
    specialty: 'General Surgery — Endoscopy, Minimally Invasive Surgery, Colorectal Surgery',
    qualifications: 'MBBS (UM), Master of Surgery (UM)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/chan-siew-how',
  },
  {
    id: '33',
    name: 'Dr. Charlotte Jane Joseph',
    department: 'Paediatrics',
    specialty: 'General Paediatrics, Developmental Paediatrics',
    qualifications: 'MBBS (Manipal), Fellowship Developmental Paediatrics (MOH Malaysia), MRCPCH (UK)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-charlotte-jane-joseph',
    extraInfo: 'Specialises in child development assessment, autism, ADHD.',
  },
  {
    id: '34',
    name: 'Dr. Chua Siew Houy',
    department: 'Internal Medicine',
    specialty: 'Internal Medicine, General Physician',
    qualifications: 'MB BCh BAO (Queen\'s University Belfast), MRCP (RCP Edinburgh), FRCP (Edinburgh)',
    languages: ['English', 'Malay', 'Mandarin'],
  },
  {
    id: '35',
    name: 'Dr. Doris Ng Sin Wen',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology',
    qualifications: 'Consultant Obstetrician and Gynaecologist',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/dr-doris-ng-sin-wen',
  },
  {
    id: '36',
    name: 'Dr. Effarezan Abdul Rahman',
    department: 'Cardiology / Internal Medicine',
    specialty: 'Internal Medicine, Cardiology — Multimodality Cardiac Imaging',
    qualifications: 'MB ChB (Cardiff, 2004), MRCP (UK, 2007), Fellowship Multimodality Cardiac Imaging',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-effarezan-abdul-rahman',
    extraInfo: 'Specialises in echocardiography, cardiac CT, and cardiac MRI.',
  },
  {
    id: '37',
    name: 'Dr. Gunasegaran PT Rajan',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology, Fetal Medicine',
    qualifications: 'MBBS (UM, 1982), MRCOG (1989), Fetal Medicine (1991), FRCOG (2002)',
    languages: ['English', 'Malay', 'Tamil'],
    extraInfo: 'Senior Consultant with subspecialty expertise in fetal medicine and high-risk pregnancies.',
  },
  {
    id: '38',
    name: 'Dr. Hilawati Binti Yusof',
    department: 'Clinical Oncology',
    specialty: 'Clinical Oncology, Radiotherapy',
    qualifications: 'MBBCh (University of Wales), FRCR (RCR London)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/hilawati-binti-yusof',
  },
  {
    id: '39',
    name: 'Dr. Hilmi Hussein',
    department: 'Anaesthesiology and Critical Care',
    specialty: 'Anaesthesiology, Critical Care, Intensive Care Medicine',
    qualifications: 'MD (UKM, reg. 1987), M.MED Anaesthesiology',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-hilmi-hussein',
    extraInfo: 'Over 39 years of experience in anaesthesiology and intensive care.',
  },
  {
    id: '40',
    name: 'Dr. Husna Musa',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology',
    qualifications: 'Consultant Obstetrician and Gynaecologist',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/husna-musa',
  },
  {
    id: '41',
    name: 'Dr. Ina Shaliny A/P Duraisamy',
    department: 'Clinical Oncology',
    specialty: 'Clinical Oncology — Radiotherapy, Systemic Cancer Treatment',
    qualifications: 'MBBS (IMU), M.Co Clinical Oncology (UM)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/ina-shaliny-ap-duraisamy',
  },
  {
    id: '42',
    name: 'Dr. Johan Ahmad',
    department: 'Orthopaedic Surgery',
    specialty: 'Orthopaedic Surgery',
    qualifications: 'MB ChB (University of Sheffield UK), MRCS Glasgow, MS Orthopaedics (UKM)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-johan-ahmad',
  },
  {
    id: '43',
    name: 'Dr. Jude Morgan A/L Marie Joseph Boniface',
    department: 'Emergency Medicine',
    specialty: 'Emergency Medicine',
    qualifications: 'MBBS, MMed (Emergency Medicine)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-jude-morgan',
    extraInfo: 'Consultant Emergency Physician at Emergency and Trauma Department.',
  },
  {
    id: '44',
    name: 'Dr. Kamalanathan Palaniandy',
    department: 'Neurosurgery',
    specialty: 'Neurosurgery — Neurospine, Endoscopic Spine Surgery, Pain Management',
    qualifications: 'MD (UKM), MS Neurosurgery (USM), Neurospine Fellowship (WFNS), AOSpine Fellowship, Endoscopic Spine Fellowship (Korea), Pain Fellowship (India)',
    languages: ['English', 'Malay', 'Tamil'],
    extraInfo: 'Expert in endoscopic spine surgery and pain management.',
  },
  {
    id: '45',
    name: 'Dr. Kasmini Kassim',
    department: 'Psychiatry',
    specialty: 'Psychiatry, Child and Adolescent Psychiatry',
    qualifications: 'MBBS (Punjab, 1975), DPM (RCPI, 1982), MRCPsych (UK, 1983), FRCPsych (1994), FAMM (1997)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-kasmini-kassim',
    extraInfo: 'Over 40 years of clinical practice.',
  },
  {
    id: '46',
    name: 'Dr. Khoo Yee Laim',
    department: 'Psychiatry',
    specialty: 'Psychiatry — Anxiety, Depression, Bipolar Disorder, Adolescent Mental Health, ADHD',
    qualifications: 'MD (USM), Master of Psychological Medicine (UM)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-khoo-yee-laim',
    extraInfo: 'Certified Cognitive Behavioural Therapy (CBT) practitioner.',
  },
  {
    id: '47',
    name: 'Dr. Kwan Jing Wern',
    department: 'Dermatology',
    specialty: 'Dermatology, Internal Medicine',
    qualifications: 'MBBS (IMU, 2008), MRCP (UK, 2014), Diploma in Dermatology (NUS, 2017), Advanced Master of Dermatology (UKM, 2021)',
    languages: ['English', 'Malay', 'Mandarin'],
  },
  {
    id: '48',
    name: 'Dr. Lee Kent Hui',
    department: 'Orthopaedic Surgery',
    specialty: 'Orthopaedic Surgery, Arthroplasty, Trauma Surgery',
    qualifications: 'MD (UPM, 2005), Masters in Orthopaedics (UKM, 2014)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-lee-kent-hui',
    extraInfo: 'Resident Consultant specialising in arthroplasty and trauma surgery.',
  },
  {
    id: '49',
    name: 'Dr. Lee Lin Ing',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology — Laparoscopic Gynaecological Surgery',
    qualifications: 'MBBS (Manipal)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/dr-lee-lin-ing',
    extraInfo: 'Over 10 years at KPJ DSH. Specialises in laparoscopic gynaecological surgery.',
  },
  {
    id: '50',
    name: 'Dr. Lim Shu Xian',
    department: 'Palliative Care / Internal Medicine',
    specialty: 'Palliative Care, Internal Medicine',
    qualifications: 'MBBS (Melaka Manipal), M.Int. Med (UM), Palliative Care Fellowship (Singapore and Malaysia)',
    languages: ['English', 'Malay', 'Mandarin'],
    extraInfo: 'Specialises in end-of-life care, pain management, and comfort-focused care.',
  },
  {
    id: '51',
    name: 'Dr. Malek Faris Riza Feisal B Jeffrizal',
    department: 'Rheumatology',
    specialty: 'Rheumatology',
    qualifications: 'Consultant Rheumatologist',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/malek-faris-riza-feisal-b-jeffrizal',
  },
  {
    id: '52',
    name: 'Dr. Milton Lum Siew Wai',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology — Minimally Invasive Surgery',
    qualifications: 'MBBS (UM, 1973), MRCOG (UK, 1979), FRCOG (UK, 1993)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/doctor/dr-milton-lum-siew-wai',
    extraInfo: 'Over 50 years of clinical experience. Former FIGO Visiting Professor.',
  },
  {
    id: '53',
    name: 'Dr. Mohamad Jeremi Jeffrey',
    department: 'Plastic and Reconstructive Surgery',
    specialty: 'Plastic Surgery, Reconstructive Surgery',
    qualifications: 'MD (Calgary, 2011), MRCSEd (2017), Master of Surgery Plastic Surgery (USM, 2021)',
    languages: ['English', 'Malay'],
  },
  {
    id: '54',
    name: 'Dr. Mohan Raj Varutha Rajoo',
    department: 'Obstetrics and Gynaecology / Reproductive Medicine',
    specialty: 'Obstetrics and Gynaecology, Reproductive Medicine — IVF, Fertility Treatment',
    qualifications: 'MBBS (India, 1997), Masters O&G (UM, 2007), Fellowship Reproductive Medicine (Queen Mary Hospital Hong Kong, 2014)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/dr-mohan-raj',
    extraInfo: 'Head of KPJ Damansara Fertility Centre. Leads IVF, ICSI, IMSI, PGS, and male infertility services.',
  },
  {
    id: '55',
    name: 'Dr. Mohd Ridzo Mahmud',
    department: 'ENT / Otorhinolaryngology',
    specialty: 'Ear, Nose and Throat Surgery — Otology (Ear sub-specialty)',
    qualifications: 'MD (UKM), FRCS (Edinburgh), Masters (UKM), Fellowship in Otology (Harvard Medical School)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-mohd-ridzo-mahmud',
    extraInfo: 'Trained at Harvard Medical School for fellowship in Otology.',
  },
  {
    id: '56',
    name: 'Dr. Mohd Shamsul Amri Ismail',
    department: 'Gastroenterology and Hepatology / Internal Medicine',
    specialty: 'Internal Medicine, Gastroenterology, Hepatology',
    qualifications: 'MBBS (Bangalore, 1997), MMed (UKM, 2006), Fellowship Hepatology (MOH Malaysia, 2011)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-mohd-shamsul-amri-ismail',
    extraInfo: 'Resident Consultant. Sub-specialises in hepatology (liver disease).',
  },
  {
    id: '57',
    name: 'Dr. Muhammad Ash-Shafhawi Adznan',
    department: 'General Surgery / Colorectal Surgery',
    specialty: 'General Surgery — Colorectal Surgery, Peritoneal Surface Malignancy (CRS/HIPEC)',
    qualifications: 'Medical degree (Hasanuddin University), Surgical accreditation (UKM); Fellowship Colorectal Surgery and Peritoneal Surface Malignancy',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/muhammad-ash-shafhawi-adznan',
    extraInfo: 'Expert in Cytoreductive Surgery (CRS) and HIPEC for peritoneal surface malignancy.',
  },
  {
    id: '58',
    name: 'Dr. Muhammad Dzafir Ismail',
    department: 'Cardiology / Internal Medicine',
    specialty: 'Internal Medicine, Cardiology — Interventional Cardiology, Endovascular Intervention',
    qualifications: 'MBBS (UM), MMED (UM), FNHAM, FESC, FSCAI, FAsCC, AM',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-muhammad-dzafir-ismail',
    extraInfo: 'Also Senior Lecturer and Consultant Cardiologist at University of Malaya.',
  },
  {
    id: '59',
    name: 'Dr. Nachiyappan V Annamalai',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology — Fertility and Minimally Invasive Gynaecological Surgery',
    qualifications: 'Consultant Obstetrician, Gynaecologist and Fertility Specialist',
    languages: ['English', 'Malay', 'Tamil'],
  },
  {
    id: '60',
    name: 'Dr. Naqiyah Ibrahim',
    department: 'General Surgery / Breast and Endocrine Surgery',
    specialty: 'General Surgery — Breast and Endocrine Surgery',
    qualifications: 'MBBS (UM, 1994), M.Med (UKM, 2001), Specialist Certification Breast Surgery (University of Hong Kong, 2006)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-naqiyah-ibrahim',
    extraInfo: 'Lead Surgeon of the Breast and Endocrine Surgery Centre at KPJ DSH.',
  },
  {
    id: '61',
    name: 'Dr. Nazatul Sabariah Ahmad',
    department: 'Paediatric Dentistry',
    specialty: 'Paediatric Dentistry',
    qualifications: 'DDS (UKM), DDent Paediatric Dentistry (University College London)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-nazatul-sabariah-bt-ahmad',
  },
  {
    id: '62',
    name: 'Dr. Ng Teck Siang',
    department: 'ENT / Otorhinolaryngology',
    specialty: 'Ear, Nose and Throat Surgery — Rhinology, Skull Base Surgery',
    qualifications: 'MD (UKM), MS ORL HNS (UM); Research Fellowship Skull Base Surgery (USA)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/dr-ng-teck-siang',
    extraInfo: 'Resident Consultant. Sub-specialises in rhinology and skull base surgery.',
  },
  {
    id: '63',
    name: 'Dr. Nik Alif Azriq Nik Abdullah',
    department: 'Orthopaedic Surgery',
    specialty: 'Orthopaedic Surgery — Foot and Ankle Sub-specialty',
    qualifications: 'MBBS (CUCMS), MS Orthopaedics (UKM)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/nik-alif-azriq-nik-abdullah',
  },
  {
    id: '64',
    name: 'Dr. Nik Nasyrah Nek Mohamad',
    department: 'Psychiatry',
    specialty: 'Psychiatry',
    qualifications: 'MD (UKM)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-nik-nasyrah-nek-mohamad',
  },
  {
    id: '65',
    name: 'Dr. Nisa Kamila Ab Rashid',
    department: 'Nuclear Medicine',
    specialty: 'Nuclear Medicine',
    qualifications: 'MBBS (Royal College of Medicine Perak, UM programme)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/nisa-kamila-ab-rashid',
  },
  {
    id: '66',
    name: 'Dr. Noraini Nadior',
    department: 'Ophthalmology',
    specialty: 'Ophthalmology, Ophthalmic Surgery',
    qualifications: 'MD (USM, 1987), M.MED (NUS, 1996), M.SURG (UM, 1996), FRCS Edinburgh (1998)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-noraini-nadior',
  },
  {
    id: '67',
    name: 'Dr. Nur Abdul Karim',
    department: 'Emergency Medicine',
    specialty: 'Emergency Medicine',
    qualifications: 'Emergency Physician',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-nur-abdul-karim',
  },
  {
    id: '68',
    name: 'Dr. Nurhayati Mokhty',
    department: 'Radiology',
    specialty: 'Diagnostic Radiology',
    qualifications: 'Consultant Diagnostic Radiologist',
    languages: ['English', 'Malay'],
  },
  {
    id: '69',
    name: 'Dr. Oommen George',
    department: 'Plastic and Reconstructive Surgery',
    specialty: 'Plastic Surgery, Reconstructive Surgery',
    qualifications: 'MBBS (Manipal), Master of Surgery Plastic Surgery (USM, 2007)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-oommen-george',
    extraInfo: 'Resident Consultant Plastic and Reconstructive Surgeon.',
  },
  {
    id: '70',
    name: 'Dr. Pavin Kaur Bal A/P Baldev Singh',
    department: 'Paediatric Surgery',
    specialty: 'Paediatric Surgery',
    qualifications: 'Consultant Paediatric Surgeon',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/pavin-kaur-bal-ap-baldev-singh',
  },
  {
    id: '71',
    name: 'Dr. Quah Jing Yao',
    department: 'Geriatric Medicine / Internal Medicine',
    specialty: 'Geriatric Medicine, Internal Medicine — Memory and Cognitive Impairment, Delirium, Falls',
    qualifications: 'Medical training at Barts and The London School of Medicine and Dentistry (UK)',
    languages: ['English', 'Malay', 'Mandarin', 'Cantonese'],
    profileUrl: 'https://kpjhealth.com.my/dr-quah-jing-yao',
    extraInfo: 'Resident Consultant Geriatrician specialising in memory disorders and falls prevention.',
  },
  {
    id: '72',
    name: 'Dr. Raja Badrul Hisham Raja Zezeman Shah',
    department: 'General Surgery / Colorectal and Bariatric Surgery',
    specialty: 'General Surgery — Laparoscopic Colorectal Surgery, Bariatric Surgery',
    qualifications: 'MB BChir (University of Liverpool, with Honours), Master of Surgery (UKM)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-raja-badrul-hisham-raja-zezeman-shah-chairman-mdac-dsh2',
    extraInfo: 'Performed over 100 laparoscopic bariatric procedures at KPJ DSH.',
  },
  {
    id: '73',
    name: 'Dr. Rajeentheran Suntheralingam',
    department: 'Urology',
    specialty: 'Urology — Endourology, Stone Surgery, Uro-Oncology, Urodynamics, Neuro-Urology',
    qualifications: 'MBBS, FRCS (Edinburgh), FRCS (Glasgow), FRCS Urology (Glasgow), MBU Urology (Malaysia)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/Dr-Rajeentheran-Suntheralingam',
    extraInfo: 'Senior Resident Consultant Urologist at KPJ DSH since 2006.',
  },
  {
    id: '74',
    name: 'Dr. Rakhee Yadav Hematram Yadav',
    department: 'Paediatrics',
    specialty: 'General Paediatrics — Paediatric Vaccination, Early Childhood Nutrition',
    qualifications: 'BSc Medical Sciences (UPM), MD (UPM), MMed Paediatrics (UM), AM (Malaysia), PG Diploma Paediatric Nutrition (Boston)',
    languages: ['English', 'Malay', 'Hindi'],
    extraInfo: 'Over 20 years of experience. Strong advocate for paediatric vaccination and early childhood nutrition.',
  },
  {
    id: '75',
    name: 'Dr. Robert Penafort',
    department: 'Orthopaedic Surgery / Rehabilitation',
    specialty: 'Orthopaedic Surgery, Trauma Surgery',
    qualifications: 'MBBS (Kerala, 1989), MMed Orthopaedics (UM, 1998 — Subramaniam Gold Medal)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor?d_id=20894',
    extraInfo: 'Clinical Head of Rehabilitation Services at KPJ DSH. Top of class (Subramaniam Gold Medal) in Masters.',
  },
  {
    id: '76',
    name: 'Dr. Rohani Effendy',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology',
    qualifications: 'Consultant Obstetrician and Gynaecologist',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-rohani-effendy',
  },
  {
    id: '77',
    name: 'Dr. Roslan Abdul Rahman',
    department: 'Dentistry / Oral and Maxillofacial Surgery',
    specialty: 'Oral and Maxillofacial Surgery',
    qualifications: 'BDS (UM, 1994), FFDRCS (RCS UK, 2000)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-roslan-abdul-rahman',
  },
  {
    id: '78',
    name: 'Dr. Rozman Md Idrus',
    department: 'Orthopaedic Surgery',
    specialty: 'Orthopaedic Surgery — Joint Replacement, Sports Medicine',
    qualifications: 'MBBS, FRCS (UK), MCh.Orth, AM',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-rozman-md-idrus',
  },
  {
    id: '79',
    name: 'Dr. Saadiah Sulaiman',
    department: 'Dermatology',
    specialty: 'Dermatology — Eczema, Psoriasis, Acne, Hair Loss, Nail Fungus, Skin Cancer, Rosacea',
    qualifications: 'MBBch, RSCI Eire; M.MED Dermatology (UKM); AM (UKM and National University of Ireland)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-saadiah-sulaiman',
  },
  {
    id: '80',
    name: 'Dr. Sabastian Tong Hung Yew',
    department: 'General Surgery / Colorectal Surgery',
    specialty: 'General Surgery, Colorectal Surgery',
    qualifications: "MBBS (St. Mary's Hospital Medical College UK, 1979), FRCS (RCS Edinburgh, 1985)",
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-sabastian-h-y-tong',
    extraInfo: "Senior Consultant trained at St. Mary's Hospital Medical College London.",
  },
  {
    id: '81',
    name: 'Dr. Sangeetha Poovaneswaran',
    department: 'Clinical Oncology',
    specialty: 'Clinical Oncology, Radiotherapy',
    qualifications: 'MD (University of Aberdeen UK)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/dr-sangeetha-poovaneswaran',
    extraInfo: 'Resident Consultant Clinical Oncologist at Cancer and Radiosurgery Centre.',
  },
  {
    id: '82',
    name: 'Dr. Shaharudeen Kamaludeen',
    department: 'Internal Medicine / Infectious Diseases',
    specialty: 'Internal Medicine, Infectious Diseases',
    qualifications: 'MBBS (India), M Internal Medicine (UM)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-shaharudeen-kamaludeen',
    extraInfo: 'Resident Consultant. Manages bacterial, viral, fungal, and parasitic infections.',
  },
  {
    id: '83',
    name: 'Dr. Shobana A/P Nadarajah',
    department: 'Ophthalmology',
    specialty: 'Ophthalmology — Refractive Cataract Surgery',
    qualifications: 'MBBS (Manipal), MS Ophthalmology (UKM)',
    languages: ['English', 'Malay', 'Tamil'],
    profileUrl: 'https://kpjhealth.com.my/cfs/doctor/dr-shobana-a-p-nadarajah',
    extraInfo: '15 years of experience. Sub-specialises in refractive cataract surgery.',
  },
  {
    id: '84',
    name: 'Dr. Sim Chaw Shian',
    department: 'Orthopaedic Surgery / Spine Surgery',
    specialty: 'Orthopaedic Surgery, Spine Surgery — Minimally Invasive Endoscopic Spinal Surgery',
    qualifications: 'MBBS (University of New South Wales, 1994), MS Orthopaedics (UKM, 2002), Fellowship Spine Surgery (NUH Singapore, 2007)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/dr-sim-chaw-shian',
    extraInfo: 'Specialist in minimally invasive endoscopic spinal surgery since 2003.',
  },
  {
    id: '85',
    name: 'Dr. Soh Lay Sian',
    department: 'Paediatrics',
    specialty: 'General Paediatrics',
    qualifications: 'MBBS (UM, 1979), DCH (RCP, 1985), MRCP (1987)',
    languages: ['English', 'Malay', 'Mandarin', 'Cantonese'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-soh-lay-sian',
    extraInfo: 'Senior Consultant Paediatrician.',
  },
  {
    id: '86',
    name: 'Dr. Song Soon Cheok',
    department: 'Cardiology / Internal Medicine',
    specialty: 'Cardiology — Cardiac Electrophysiology, Internal Medicine',
    qualifications: 'MB ChB (University of Edinburgh UK), MRCP (RCP UK)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/dr-song-soon-cheok',
    extraInfo: 'Sub-specialises in cardiac electrophysiology (heart rhythm disorders). Trained at University of Edinburgh.',
  },
  {
    id: '87',
    name: 'Dr. Susanna Huam Siew Hoon',
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology',
    qualifications: 'MBBS (India), M.MED O&G (UM)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-susanna-huam-siew-hoon',
    extraInfo: 'Resident Consultant Obstetrician and Gynaecologist.',
  },
  {
    id: '88',
    name: 'Dr. Tan Tean Tune',
    department: 'Internal Medicine / Endocrinology',
    specialty: 'Internal Medicine, Endocrinology — Diabetes, Thyroid, Hormonal Disorders',
    qualifications: 'MD (UKM, 1982), MRCP (RCP UK, 1987), FRCP (RCP UK, 1994), MRCP (RCP&S Glasgow, 1995)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/dr-tan-tean-tune',
    extraInfo: 'Senior Consultant. Holds multiple Royal College of Physicians fellowships from UK and Glasgow.',
  },
  {
    id: '89',
    name: 'Dr. Tiang Soon Wee',
    department: 'Cardiology / Internal Medicine',
    specialty: 'Cardiology — Interventional Cardiology, Internal Medicine',
    qualifications: 'MBBS (UM, 1996), MRCP (RCP UK, 2000)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-tiang-soon-wee',
    extraInfo: 'Resident Consultant Cardiologist specialising in interventional cardiology.',
  },
  {
    id: '90',
    name: 'Dr. Toh Zeng Yan',
    department: 'Geriatric Medicine / Internal Medicine',
    specialty: 'Geriatric Medicine, Internal Medicine',
    qualifications: 'MBBS (Manipal), MMed Internal Medicine (UM), Fellowship Geriatric Medicine (MOH Malaysia)',
    languages: ['English', 'Malay', 'Mandarin'],
    profileUrl: 'https://kpjhealth.com.my/dr-toh-zeng-yan',
  },
  {
    id: '91',
    name: 'Dr. Yusniza Yusoff',
    department: 'Endocrinology / Internal Medicine',
    specialty: 'Internal Medicine, Endocrinology — Diabetes, Thyroid Disorders, Hormonal Imbalances',
    qualifications: 'MD (USM), Masters Internal Medicine (UKM), Fellowship Endocrinology (MOH Malaysia)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/dr-yusniza-yusoff',
    extraInfo: 'Over 20 years of clinical experience. Specialises in diabetes management and thyroid disorders.',
  },
  {
    id: '92',
    name: "Prof. Dato' Dr. Haron Ahmad",
    department: 'General Surgery / Bariatric Surgery / HPB Surgery',
    specialty: 'General Surgery — Hepatopancreatobiliary Surgery, Laparoscopic Surgery, Bariatric Surgery',
    qualifications: 'MD, M.Surg (General Surgery)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/prof-dato-dr-haron-ahmad',
    extraInfo: 'Head of Bariatric and Advanced Laparoscopic Surgical Centre at KPJ DSH. Professor of Surgery.',
  },
  {
    id: '93',
    name: 'Prof. Dr. Imelda Nasreen Nasruddin @ Balchin',
    department: 'Obstetrics and Gynaecology / Maternal and Fetal Medicine',
    specialty: 'Obstetrics and Gynaecology — Maternal and Fetal Medicine, High-Risk Pregnancies',
    qualifications: 'MBBS; Subspecialist accreditation Maternal and Fetal Medicine (RCOG UK); trained at University of Manchester and Imperial College London',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-imelda-nasreen-nasruddin-balchin',
    extraInfo: 'Professor. Leads the Preterm Birth Prevention Clinic.',
  },
  {
    id: '94',
    name: 'Prof. Dr. Mohd Shazli Draman @ Yusof',
    department: 'Endocrinology / Internal Medicine',
    specialty: 'Endocrinology — Thyroidology, Autoimmune Thyroid Disease, Diabetes Mellitus',
    qualifications: 'MB BCh BAO (Trinity College Dublin, 2001), MRCP (RCPI, 2010), CCT Endocrinology and Diabetes Mellitus (RCPI, 2010)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/dr-mohd-shazli-draman-yusof',
    extraInfo: 'Professor. Spent 28 years in Ireland and the UK. Highly specialised in thyroidology.',
  },
  {
    id: '95',
    name: "Prof. Emeritus Dato' Dr. Azizi Hj Omar",
    department: 'Paediatrics / Paediatric Respiratory Medicine',
    specialty: 'Paediatrics, Paediatric Respiratory Medicine — Asthma, Lung Conditions in Children',
    qualifications: 'MBBS (Australia), MRCP (UK), FRCP (Edinburgh and Glasgow)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/prof-dato-dr-azizi-hj-omar',
    extraInfo: 'Professor Emeritus of Paediatrics. Formerly on KPJ Healthcare Board of Directors.',
  },
  {
    id: '96',
    name: 'Puan Sri Datuk Dr. Suraiya Hani Hussein',
    department: 'Dermatology / Internal Medicine',
    specialty: 'Internal Medicine, Dermatology',
    qualifications: 'MBBS (Malaya), MRCP (UK), FRCP (London), Dip. Derm (London) — St John\'s Institute of Dermatology, University of London',
    languages: ['English', 'Malay'],
    profileUrl: "https://kpjhealth.com.my/puan-sri-datuk-dr-suraiya-hani-hussein",
    extraInfo: "Resident Consultant. Trained at St John's Institute of Dermatology, one of the world's leading dermatology centres.",
  },
  {
    id: '97',
    name: "To' Puan Dr. Maziah Ahmad Mahidin",
    department: 'Obstetrics and Gynaecology',
    specialty: 'Obstetrics and Gynaecology — Endometriosis, Female Health, Pregnancy',
    qualifications: 'MD (UKM), Master in O&G, MRCOG (London)',
    languages: ['English', 'Malay'],
    profileUrl: 'https://kpjhealth.com.my/damansara/doctor/to-puan-dr-maziah-ahmad-mahidin',
    extraInfo: 'One of the founding members of KPJ Damansara Specialist Hospital medical team since 1997. Specialises in endometriosis.',
  },
]

export const SPECIALTIES = [...new Set(DOCTORS.map(d => d.department))].sort()
